services:
  mongodb:
    image: mongo:8.0
    container_name: HRMS-db
    restart: always
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: good1234
      MONGO_INITDB_DATABASE: HRMS
    volumes:
      - ./database/data/db:/data/db
      # - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - hrms-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "4"

  nginx:
    image: nginx:alpine
    container_name: HRMS-nginx
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./release.zip:/etc/nginx/html/public/release.zip:ro
    depends_on:
      - backend
      - frontend
    networks:
      - hrms-network
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "4"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: HRMS-backend
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3000
      - NODE_ENV=${NODE_ENV}
      - TZ=Asia/Taipei
      - SYSTEM_START_DATE=${SYSTEM_START_DATE}
    ports:
      - "${BACKEND_PORT}:3000"
    depends_on:
      - mongodb
    networks:
      - hrms-network
    restart: unless-stopped
    volumes:
      - ${DATA}:/app/data
      - ./backend/uploads:/app/uploads
      - .:/workspace
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "4"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      # platforms:
      #   - "linux/amd64"
    container_name: HRMS-frontend
    expose:
      - "80"
    environment:
      - name=value
      - TZ=Asia/Taipei
    depends_on:
      - backend
    networks:
      - hrms-network
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "4"

  # The dedicated Scheduler container
  scheduler:
    image: mcuadros/ofelia:latest
    container_name: HRMS-scheduler
    depends_on:
      - backend
    # Mount the config file we wrote above
    volumes:
      - ./ofelia.ini:/etc/ofelia/config.ini:ro
    networks:
      - hrms-network
      # If you want to use "job-exec" to trigger things inside other containers,
      # you must pass the docker socket:
      # - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  hrms-network:
    driver: bridge