# ofelia.ini

# JOB 1: Triggers your data-sync API every hour
[job-local "auto-attendance-record-creation"]
schedule = @hourly
command = sh -c 'wget --post-data=\"\" --header=\"x-cron-token: super_secret\" -O- http://backend:3000/api/attendance/create/now'
no-overlap = true

; # JOB 2: Clears caches every 15 minutes
; [job-local "api-cache-clear"]
; schedule = @every 15m
; command = curl -X POST http://app:8080/api/cron/cache-clear -H "x-cron-token: super_secret"

; # JOB 3: Runs a database backup inside your Postgres container (job-exec)
; [job-exec "db-backup"]
; schedule = 0 2 * * *
; container = database-service
; command = pg_dump -U postgres mydb > /backup/backup.sql