import { Holiday } from '../models';
import { APIError } from '../middleware/errorHandler';

export class HolidaySeedService {
  /**
   * Generate all Saturdays and Sundays for a given year
   */
  async seedWeekendHolidays(year: number): Promise<{ created: number; skipped: number }> {
    let created = 0;
    let skipped = 0;

    // Start from January 1st of the year
    const startDate = new Date(year, 0, 1);
    const endDate = new Date(year, 11, 31);

    const currentDate = new Date(startDate);

    while (currentDate <= endDate) {
      const dayOfWeek = currentDate.getDay();

      // 0 = Sunday, 6 = Saturday
      if (dayOfWeek === 0 || dayOfWeek === 6) {
        const dateStr = currentDate.toISOString().split('T')[0];
        const dayName = '例假日';

        // Check if holiday already exists for this date
        const existing = await Holiday.findOne({ date: currentDate });

        if (!existing) {
          try {
            await Holiday.create({
              date: new Date(currentDate),
              type: '例假日',
              name: dayName,
              pay_rate: 1.0,
              is_paid: true,
              memo: `${year}年自動產生的週末假日`
            });
            created++;
          } catch (error) {
            console.error(`Failed to create holiday for ${dateStr}:`, error);
          }
        } else {
          skipped++;
        }
      }

      // Move to next day
      currentDate.setDate(currentDate.getDate() + 1);
    }

    return { created, skipped };
  }

  /**
   * Generate all Saturdays and Sundays for a date range
   */
  async seedWeekendHolidaysByRange(
    startYear: number,
    endYear: number
  ): Promise<{ totalCreated: number; totalSkipped: number; years: any[] }> {
    const results = [];
    let totalCreated = 0;
    let totalSkipped = 0;

    for (let year = startYear; year <= endYear; year++) {
      const result = await this.seedWeekendHolidays(year);
      totalCreated += result.created;
      totalSkipped += result.skipped;
      results.push({
        year,
        created: result.created,
        skipped: result.skipped
      });
    }

    return {
      totalCreated,
      totalSkipped,
      years: results
    };
  }

  /**
   * Clear all weekend holidays (例假日 with memo containing "自動產生")
   */
  async clearAutoGeneratedWeekendHolidays(): Promise<number> {
    const result = await Holiday.deleteMany({
      type: '例假日',
      memo: { $regex: /自動產生的週末假日/ }
    });

    return result.deletedCount || 0;
  }
}

// Export singleton instance
export const holidaySeedService = new HolidaySeedService();
