import { Router } from 'express';
import { holidayController } from '../controllers/holidayController';
import { authenticateToken, requireRole } from '../middleware/auth';

const router = Router();

// All routes require authentication
router.use(authenticateToken);

// All routes require HR or Admin role
router.use(requireRole(['hr', 'admin']));

// Read routes (HR/Admin only)
router.get('/', holidayController.getAllHolidays);
router.get('/range', holidayController.getHolidaysByDateRange);
router.get('/check/:date', holidayController.checkIsHoliday);
router.get('/:id', holidayController.getHolidayById);

// Seed routes (HR/Admin only)
router.post('/seed/weekends', holidayController.seedWeekendHolidays);
router.delete('/seed/weekends', holidayController.clearAutoGeneratedWeekends);

// Write routes (HR/Admin only - already protected by requireRole above)
router.post('/', holidayController.createHoliday);
router.put('/:id', holidayController.updateHoliday);
router.delete('/:id', holidayController.deleteHoliday);

export default router;
